### ISSUE TITLE
Using autoloader in command

### ISSUE THREAD

**Issue by qpautrat** [creads/api2symfony-bundle#5]
I dont know how this line can work; https://github.com/creads/api2symfony-bundle/blob/master/src/Command/RamlGenerateCommand.php#L43

Autoload always will already be required before. So `$loader` will always be `true`.
https://github.com/creads/api2symfony-bundle/blob/master/src/Command/RamlGenerateCommand.php#L48 Will raise an error every time.

@pitpit ?

**Comment by pitpit** [comment]
Actually, $loader will be set with the value returned in the file `app/autoload.php`, which is the composer class loader

I need the loader to find real path to the the directory where controllers stand in the bundle : https://github.com/creads/api2symfony-bundle/blob/master/src/Command/RamlGenerateCommand.php#L48 but i did not find another way to properly retrieve the composer loader
